export { default as Dialogue } from "./Dialogue"
export { default as Furigana } from "./Furigana"
export { default as Header } from "./Header"
export { default as Line } from "./Line"
export { default as SpeechBubble } from "./SpeechBubble"